name: Lint & Format Check

on:
  push:
    branches: [ main ]
    paths:
      - 'Frontend/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'Frontend/**'

jobs:
  lint:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Frontend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 22 with npm cache
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: Frontend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run Angular ESLint
        run: npm run lint

      - name: Run Prettier check
        run: npm run format:check